from enum import Enum
from typing import Any, Dict, List, Optional, cast, Literal
from datetime import datetime
from pathlib import Path
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, field_validator, ConfigDict


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AnalysisCategory(str, Enum):
    CODE_STRUCTURE = "code_structure"
    MAINTAINABILITY = "maintainability"
    SECURITY = "security"
    PERFORMANCE = "performance"


class ContentMode(str, Enum):
    FULL = "full"
    SIGNATURE = "signature"


class ProjectCapsule(BaseModel):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
    )

    version: int = Field(default=2, description="Capsule version schema")
    created_at: datetime = Field(default_factory=datetime.now)
    python_version: str
    project_root: Path
    project_name: str
    files_count: int
    total_size_bytes: int
    files: List["CapsuleFile"] = Field(description="File entries in the capsule")


class CapsuleFile(BaseModel):
    path: Path
    size_bytes: int
    content: Optional[str] = None

    @field_validator("path")
    @classmethod
    def validate_path(cls, v):
        return v


class PatternEvidence(BaseModel):
    file_path: Path
    line_start: Optional[int] = None
    line_end: Optional[int] = None
    pattern_type: str
    message: str
    evidence: Dict[str, Any] = Field(default_factory=dict)


class AnalysisResult(BaseModel):
    analyzer_name: str
    file_path: Optional[Path] = None
    line_start: Optional[int] = None
    line_end: Optional[int] = None
    pattern_type: str
    severity: Severity
    category: AnalysisCategory
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)
    message: str
    evidence: Dict[str, Any] = Field(default_factory=dict)
    remediation: List[str] = Field(default_factory=list)
    project_name: Optional[str] = None


class CrossProjectPattern(BaseModel):
    pattern_type: str
    severity: Severity
    category: AnalysisCategory
    projects_count: int
    projects: List[str]
    evidence: Dict[str, Any] = Field(default_factory=dict)
    message: str
    projects_confidence: float = Field(ge=0.0, le=1.0)


class ProjectAnalysisReport(BaseModel):
    project_name: str
    analyzed_at: datetime = Field(default_factory=datetime.now)
    project_path: Path
    results: List[AnalysisResult] = Field(default_factory=list)
    summary: Dict[str, Any] = Field(default_factory=dict)
    cross_project_patterns: List[CrossProjectPattern] = Field(default_factory=list)


class CorpusAnalysisReport(BaseModel):
    analyzed_at: datetime = Field(default_factory=datetime.now)
    projects_count: int
    total_findings: int
    results_by_project: Dict[str, ProjectAnalysisReport] = Field(default_factory=dict)
    global_summary: Dict[str, Any] = Field(default_factory=dict)
    cross_project_patterns: List[CrossProjectPattern] = Field(default_factory=list)


class TriageResult(BaseModel):
    """
    Output from Planner.triage() - automatic decision about which findings need LLM analysis.

    Bridges Phase 1/4 (static data) with Phase 5 (intelligent orchestration).
    """
    all_findings: List[AnalysisResult] = Field(
        description="All findings from Phase 1 (no filtering)"
    )
    llm_worthy_findings: List[AnalysisResult] = Field(
        description="Subset of findings that warrant LLM analysis (CRITICAL, HIGH+conf, patterns)"
    )
    routing: Dict[str, str] = Field(
        description="Mapping of finding_pattern_type → persona_name for routing"
    )
    token_estimate: int = Field(
        ge=0,
        description="Estimated tokens needed for this batch of LLM calls"
    )


class CodePatch(BaseModel):
    """
    Represents a single code patch suggested by the LLM.
    """
    model_config = ConfigDict(frozen=True)
    file_path: Path = Field(..., description="The target file to be patched")
    patch_type: Literal["REPLACE_LINES", "INSERT_BEFORE", "INSERT_AFTER", "DELETE_LINES"] = Field(
        ..., description="The type of patch operation to perform"
    )
    start_line: int = Field(..., description="The start line (1-indexed) for the operation")
    end_line: int = Field(..., description="The end line (1-indexed) for the operation")
    content: str = Field(..., description="The new code content to insert or replace")
    explanation: str = Field(..., description="Brief justification from LLM for this patch")


class GeneratedTest(BaseModel):
    """
    Represents a single test case generated by the LLM.
    """
    model_config = ConfigDict(frozen=True)
    file_path: Path = Field(..., description="The target file for this test (e.g., tests/test_module.py)")
    test_name: str = Field(..., description="The test function name (e.g., test_edge_case_for_x)")
    content: str = Field(..., description="The complete Python code for the test")
    explanation: str = Field(..., description="Brief justification of what this test covers")


class ExtractedArtifacts(BaseModel):
    """
    Collection of all artifacts extracted from an LLM response.
    This is the schema that ArtifactParser will return.
    """
    model_config = ConfigDict(frozen=True)
    patches: List[CodePatch] = Field(
        default_factory=list,
        description="List of suggested code patches"
    )
    tests: List[GeneratedTest] = Field(
        default_factory=list,
        description="List of generated test cases"
    )


class ExpertRecommendation(BaseModel):
    """
    Output from a single Persona's LLM analysis for one finding.
    """
    finding_id: str = Field(
        description="Unique identifier of the original finding"
    )
    persona: str = Field(
        description="Which specialist analyzed this (e.g., 'security_analyst', 'refactor_gpt')"
    )
    analysis: str = Field(
        description="LLM response text (expert analysis)"
    )
    artifacts: ExtractedArtifacts = Field(
        default_factory=ExtractedArtifacts,
        description="Parsed artifacts (code patches, test cases, etc.)"
    )
    confidence: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="Confidence in this recommendation"
    )


class EnrichedReport(BaseModel):
    """
    Final output from Phase 5 (AuditAgent orchestration).

    Combines:
    - All static findings (Phase 1/2)
    - Cross-project patterns (Phase 4)
    - Expert recommendations from orchestrated LLM analysis (Phase 5)
    """
    findings: List[AnalysisResult] = Field(
        description="All findings from static analysis (Phase 1/2/4)"
    )
    patterns: List[CrossProjectPattern] = Field(
        default_factory=list,
        description="Cross-project patterns detected in Phase 4"
    )
    triage: TriageResult = Field(
        description="Triage results from Planner (what went to LLM and why)"
    )
    expert_recommendations: List[ExpertRecommendation] = Field(
        default_factory=list,
        description="LLM-generated insights from orchestrated specialists"
    )
    execution_time: float = Field(
        description="Total execution time (all phases)"
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="When this report was generated"
    )


ProjectCapsule.model_rebuild()